version: "3.8"

services:
  app:
    build: .
    container_name: my_ratelimiter_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - kafka
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379 
      - KAFKA_BROKER=kafka:9092
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  kafka:
    image: bitnami/kafka:latest  
    container_name: kafka_broker
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
